### ISSUE TITLE
add aoa curves to wordbankr package

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank-book#10]
Justin Halberda was interested in this functionality. More generally, as people do AoA prediction, it's going to get much more important that these be generated dynamically. (Also we compute AoAs in various different parts of the book, they should be getting computed and cached using uniform functions from the package, not ad hoc).

**Comment by mikabr** [comment]
the most common way this gets done in various places is something like
```
fit_aoa <- function(word_data) {
  model <- glm(cbind(num_true, num_false) ~ age, word_data,
               family = "binomial")
  aoa <- -coef(model)[["(Intercept)"]] / coef(model)[["age"]]
  return(aoa)
}
```

are there any foreseeable issues with this computation? otherwise, the rest of the work is just making sure the function takes data in a format that's going to be clear and convenient to the user.

**Comment by mcfrank** [comment]
I was hoping it could take a `method` argument, with `bayes`, `empirical`,
`robust`, and `glm` being the possibilities. We could make `bayes` the
default then if we wanted?

I was also hoping for a `percentile` argument with `50` the default.

Mike
