### ISSUE TITLE
consolidate ASL data into a single "form"

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank-book#19]
since different forms have different items, we will basically never use these data unless we coerce all the items into a single "form" ... this is more or less what we're doing with the `French (France)` data. Maybe @daniellekellier can weigh in on whether this is hard to do on the import end? 

do we think this is a reasonable thing to do, also?

**Comment by mcfrank** [comment]
decision - do this in the book code, not in wordbank.

**Comment by mikabr** [comment]
I think this wouldn't actually make the ASL data go in anywhere – the vocab chapter filters to n > 200 (ASL combined has 59), and the vocab demographics chapters filter to having at least 4 kids in each group at each age (which this definitely doesn't have).
