### ISSUE TITLE
why so few girls in hebrew WG?

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank-book#43]

**Comment by mcfrank** [comment]
see chapter 3 figure, there is no gender data in the webapp

**Comment by mikabr** [comment]
The counts going into the figure seem to be exactly the same as the original counts in the raw data. Maybe they just had a really skewed sample?

Not sure why it isn't showing up on the shiny app, it's probably doing some filtering/exclusion.

**Comment by mikabr** [comment]
@vmarchman plans to ask hila

**Comment by mcfrank** [comment]
closing this... in the end, it is one of many idiosyncrasies across datasets, not as egregious as some of the mandarin stuff?
