### ISSUE TITLE
german and mexican spanish momed

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank-book#44]
appear to be broken, important to check the source data.

**Comment by mikabr** [comment]
@vmarchman is going to double-check the spanish coding in the manual.

@mcfrank do you know where the german data came from? am having trouble finding any way to verify the coding.

**Comment by mcfrank** [comment]
from gisela szagun:

Column 4 = SES measured as mothers’ educational level

1 = 9 years schooling
2 = 10 years schooling
3 = 13 years schooling
4 = 13 years schooling + University education

In addition to the years of schooling, there are differences in the types of schools. There is
streaming in the German school system: the group with 9 years schooling are low achievers,
the 10-year group are middle achievers, the 13 year group are high achievers (grammar
school). However, one can move up in the system, if one does well, and the 9 or 10 year
schooling is followed by a highly qualified system of apprenticeship + more schooling related
to the kind of work apprenticeship.

So we can conclude that the missing graduate education is because it was not coded.

**Comment by mikabr** [comment]
Mexican Spanish WG
![image (1)](https://user-images.githubusercontent.com/1414971/56604039-efe8ad00-65b5-11e9-8838-18c31a39fd67.png)

Mexican Spanish WS
![image](https://user-images.githubusercontent.com/1414971/56604040-f0814380-65b5-11e9-8b02-539d37202c5a.png)
