### ISSUE TITLE
need a palette for languages

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank-book#5]
solarized doesn't have enough levels

also it would be great to decide on whether we want to direct-label languages (e.g., by last point) and figure out some generalizable code to do this in plots.

**Comment by daniellekellier** [comment]
If you want to generate a new color palette depending on the number of categories available, perhaps you could check out colorspace? It looks like that package has cool functions for generating [HCL-based palettes](https://cran.r-project.org/web/packages/colorspace/vignettes/hcl-colors.pdf).

**Comment by mikabr** [comment]
this is now settable in `_common.R`
