### ISSUE TITLE
_output.yml includes missing analytics_token.html file

### ISSUE THREAD

**Issue by mikabr** [langcog/wordbank-book#59]

**Comment by mcfrank** [comment]
there is a crazy error here where analytics doesn't seem to want to
generate the token for our property. I have no idea why.

**Comment by mikabr** [comment]
I'm confused, where are these analytics coming from?

**Comment by mcfrank** [comment]
google analytics... I set up a new "property" and try to generate an
analytics token as you would normally, and get some weird site error.

>

**Comment by mcfrank** [comment]
can't fix this, giving up on analytics.
