### ISSUE TITLE
address Philip's comments on chapter 15 and 16

### ISSUE THREAD

**Issue by vmarchman** [langcog/wordbank-book#75]
[Chapter 15_PD.docx](https://github.com/langcog/wordbank-book/files/3139857/Chapter.15_PD.docx)
[Chapter 16_PD.docx](https://github.com/langcog/wordbank-book/files/3139858/Chapter.16_PD.docx)

**Comment by mikabr** [comment]
chapter 15:
https://docs.google.com/document/d/1jg-nihFr3gZ4aqkp4trYXPAqwsqIgnPZtAkVzS_WBSw/edit

chapter 16:
https://docs.google.com/document/d/1HeZspkowd2JRZpEpRE6yC24JNIbXL4A7vISSJeEimgU/edit?usp=sharing
