### ISSUE TITLE
fix missing parts of cross-lag coefficients in grammar-lex

### ISSUE THREAD

**Issue by mikabr** [langcog/wordbank-book#79]

**Comment by mikabr** [comment]
a few other issues in this section:
- p=0 p-values
- some variables in figures 13.10 and 13.11 aren't defined
- why are 13.10 and 13.11 mirror images compared to each other?

**Comment by mcfrank** [comment]
nailed it.

**Comment by mikabr** [comment]
fyi a bunch of stuff was missing in the table again, solved by clearing out the cache – so there might be a persistent issue that causes them to get messed up when cached? no idea.
