### ISSUE TITLE
Australian English vocab comp is broken

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank-book#8]
I think this has to do with the fact that there are no registered function words (maybe category is named differently)? As a result, `prop_vocab` for WS is mostly `NA`.

**Comment by mikabr** [comment]
This is not a bug -- the Australian CDI just doesn't have function words on it
<img width="476" alt="Screenshot 2019-04-24 09 57 36" src="https://user-images.githubusercontent.com/1414971/56678389-6e595380-6677-11e9-82b5-7320ae4c0881.png">
