### ISSUE TITLE
note clear how to cite book

### ISSUE THREAD

**Issue by ebergelson** [langcog/wordbank-book#80]
help i want to cite your book and can't figure out the right ref and i'm sure you'd rather ppl do a consistent thing and not just cite the JCL or Open Mind papers?

**Comment by mcfrank** [comment]
Frank, M. C., Braginsky, M., Marchman, V. A., and Yurovsky, D. (in prep). Variability and Consistency in Early Language Learning: The Wordbank Project. Cambridge, MA: MIT Press.

**Comment by mcfrank** [comment]
thanks
