### ISSUE TITLE
ship the book!

### ISSUE THREAD

**Issue by mikabr** [langcog/wordbank-book#87]
- [x] preface
- [x] chapter 1 intro-theory
- [x] chapter 2 intro-practical
- [x] chapter 3 methods-and-data
- [x] chapter 4 psychometrics
- [x] chapter 5 vocabulary
- [x] chapter 6 demographics
- [x] chapter 7 gesture
- [x] chapter 8 items-consistency
- [x] chapter 9 items-demographics
- [x] chapter 10 items-prediction
- [x] chapter 11 categories-syntactic
- [x] chapter 12 categories-semantic
- [x] chapter 13 grammar
- [ ] chapter 14 overregularization
- [x] chapter 15 style
- [x] chapter 16 conclusion-consistency
- [x] chapter 17 conclusion-scale
- [x] chapter 18 conclusion-beyond-cdi
- [x] appendix A data
- [x] appendix B variability
- [x] appendix C stitching
- [x] appendix D aoa

**Comment by mcfrank** [comment]
checkmarks indicate that I've done a final(ish) pass on these.

@dyurovsky is assigned 7 and 8. :)

@vmarchman would be awesome if you took a look at 14 and 15?

I'm currently working on 15-18.

**Comment by vmarchman** [comment]
VM has looked at 15, 16, 17 and 18

**Comment by mcfrank** [comment]
OK, my goal is to have my last three done by end of the weekend.

**Comment by mcfrank** [comment]
I have taken a pass through all the chapters that exist!
