### ISSUE TITLE
ch8 consistent words

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank-book#88]
I took a pass through here - I demoted the status of the production/comprehension AoA correlation, that didn't seem like it merited a full chapter section? Do you feel ok about that, Dan? 

Other:
- [x] the big tables probably can use some formatting help, captions are cutoff?  @mikabr 
- [x] might be nice to give counts of how many words are shared in the top 10 across languages? I do this in talks informally a lot @dyurovsky - I often bold those that are shared across more than N langs?
- [x] dendrogram is a little bit cruder than the similar one in Ch10 - in particular, it's a bit of an advance to color the language families, and it's a little odd to have them differ in presentation style?

**Comment by mikabr** [comment]
fixed the tables

**Comment by dyurovsky** [comment]
thanks, Mika! I just did the rest, I think.
