### ISSUE TITLE
ch10 - aoapred

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank-book#89]
did some text edits on this to make it feel more "booky". @dyurovsky now should render - there was some legacy nest/unnest stuff happening plus some cache issues. 

- [x] minor header issue on Table 10.1 - kableExtra not producing the superordinate table lables
- [x] Cyrillic not rendering in Fig 10.1

**Comment by mikabr** [comment]
thanks mike! I fixed the issues with table 10.1. the cyrillic is showing up fine for me -- is it not working for you locally or on the website?

**Comment by mcfrank** [comment]
looks fine on the website, must be a local issue for me.
